# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# English (Default)
en:
  languageCode: en-us
  contentDir: content/en
  title: "Zijin Zhou's Portfolio"

# Chinese
zh:
  languageCode: zh-Hans
  contentDir: content/zh
  title: "周子瑾的个人网站"
  params:
    description: 周子瑾的个人学术网站
